#!/bin/sh
set -eu

case "${1-}" in
  restart)
    exec /usr/bin/systemctl reboot
    ;;
  shutdown)
    exec /usr/bin/systemctl poweroff
    ;;
  *)
    echo "Usage: piframe-system-action {restart|shutdown}" >&2
    exit 64
    ;;
esac
