import type { DisplaySettings } from "../../../core/settings.js";

export function renderPresentationPanel(active: boolean, display: DisplaySettings, allFolders: boolean, folderChecks: string): string {
  const selected = (name: string, value: string): string => display[name as keyof DisplaySettings] === value ? " selected" : "";
  return `<section class="panel" data-panel="presentation"${active ? "" : " hidden"}><div class="card"><form method="post" action="/admin/presentation/save">
  <section class="section"><h3>Photo source</h3><label><input id="all-folders" type="checkbox" name="useAllFolders"${allFolders ? " checked" : ""}> Use all albums</label><div id="folder-choices" class="folders">${folderChecks}</div></section>
  <section class="section"><h3>Playback</h3><label class="inline-field"><span>Seconds per photo:</span><input type="number" name="photoDurationSeconds" min="3" max="3600" value="${display.photoDurationSeconds}" required></label><label class="inline-field"><span>Ordering:</span><select name="orderMode"><option value="random"${selected("orderMode", "random")}>Random</option><option value="filename-asc"${selected("orderMode", "filename-asc")}>Filename A-Z</option><option value="filename-desc"${selected("orderMode", "filename-desc")}>Filename Z-A</option><option value="upload-newest"${selected("orderMode", "upload-newest")}>Newest upload first</option><option value="upload-oldest"${selected("orderMode", "upload-oldest")}>Oldest upload first</option></select></label><label class="inline-field"><span>Layout:</span><select name="screenLayout"><option value="single"${selected("screenLayout", "single")}>One photo</option><option value="multiple"${display.screenLayout !== "single" ? " selected" : ""}>Adaptive</option></select></label></section>
  <section class="section"><h3>Appearance</h3><label class="inline-field"><span>Image sizing:</span><select name="imagePresentationMode"><option value="fit"${display.imagePresentationMode !== "fill" ? " selected" : ""}>Fit entire photo</option><option value="fill"${display.imagePresentationMode === "fill" ? " selected" : ""}>Fill and Crop</option></select></label><label><input type="checkbox" name="clockEnabled"${display.clockEnabled ? " checked" : ""}> Show clock</label><label class="field">Clock format<select name="clockFormat"><option value="locale-default"${selected("clockFormat", "locale-default")}>Device default</option><option value="12h"${selected("clockFormat", "12h")}>12-hour</option><option value="24h"${selected("clockFormat", "24h")}>24-hour</option></select></label><label class="field">Clock size<select name="clockSize"><option value="small"${selected("clockSize", "small")}>Small</option><option value="medium"${selected("clockSize", "medium")}>Medium</option><option value="large"${selected("clockSize", "large")}>Large</option></select></label><label><input type="checkbox" name="clockShowDate"${display.clockShowDate ? " checked" : ""}> Show date</label><label><input type="checkbox" name="weatherEnabled"${display.weatherEnabled ? " checked" : ""}> Show weather</label><label><input type="checkbox" name="weatherShowCurrent"${display.weatherShowCurrent ? " checked" : ""}> Current conditions</label><label><input type="checkbox" name="weatherShowForecast"${display.weatherShowForecast ? " checked" : ""}> 5-day forecast</label><label class="field">Weather units<select name="weatherUnits"><option value="imperial"${selected("weatherUnits", "imperial")}>Imperial (°F, mph)</option><option value="metric"${selected("weatherUnits", "metric")}>Metric (°C, km/h)</option></select></label></section>
  <button class="save" type="submit" disabled>Save changes</button>
</form></div></section>`;
}
